//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_Centauri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCollege
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCollege()
        {
            this.tblRegistrations = new HashSet<tblRegistration>();
        }
    
        public int CollegeId { get; set; }
        public string CollegeName { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> StateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegistration> tblRegistrations { get; set; }
    }
}
