//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_Centauri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCertificate
    {
        public int CertificateId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string CertificateNo { get; set; }
        public string Certificate { get; set; }
    
        public virtual tblRegistration tblRegistration { get; set; }
    }
}
