//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_Centauri.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblEnquiry
    {
        [Required(ErrorMessage = "Please Enter Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Mobile Number is required.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Please Enter Valid Mobile Number.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please Enter Email")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter Your Reffer Code")]
        public string RefferBy { get; set; }
        [StringLength(100, MinimumLength = 15, ErrorMessage = "Must be at least 15 characters & maximum 100 ")]
        public string Query { get; set; }
        public int EnquiryId { get; set; }
        [DisplayName("Courses")]
        [Required(ErrorMessage = "Please Choose Your Course")]
        public Nullable<int> CourseId { get; set; }
        [DisplayName("Courses")]
        public virtual tblCourse tblCourse { get; set; }
    }
}
