//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beta_Centauri.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tblRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRegistration()
        {
            this.tblCertificates = new HashSet<tblCertificate>();
        }
    
        public int StudentId { get; set; }
        public string CenterCode { get; set; }
        [Required(ErrorMessage = "Please Enter Your Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please Enter Your State")]
        public Nullable<int> StateId { get; set; }
        [Required(ErrorMessage = "Please Enter Your District")]
        public Nullable<int> DistrictId { get; set; }
        [Required(ErrorMessage = "Please Enter Your College")]
        public Nullable<int> CollegeId { get; set; }
        [Required(ErrorMessage = "Please Enter Year")]
        public string Year { get; set; }
        [Required(ErrorMessage = "Please Enter Your Semester")]
        public string Semester { get; set; }
        [Required(ErrorMessage = "Please Enter Your Stream")]
        public Nullable<int> StreamId { get; set; }
        [Required(ErrorMessage = "Please Enter Your Branchr")]
        public Nullable<int> BranchId { get; set; }
        [Required(ErrorMessage = "Please Enter Your Course")]
        public Nullable<int> CourseId { get; set; }
        [Required(ErrorMessage = "Mobile Number is required.")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Please Enter Valid Mobile Number.")]
        public string Mobile { get; set; }
        [Required(ErrorMessage = "Please Select your DOB")]
        public Nullable<System.DateTime> DOB { get; set; }
        [Required(ErrorMessage = "Please Select your Gender")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Please Select your BloodGroup")]
        public Nullable<int> BloodGroupId { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        [Required(ErrorMessage = "Email Id is required")]
        public string EmailId { get; set; }
        [Required(ErrorMessage = "Please Enter Your Fathers Name")]
        public string FatherName { get; set; }
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "Please Select your Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Upload Your Photo")]
        public string UploadPhoto { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string RegistrationNo { get; set; }
        public string CertificateNo { get; set; }
        public string Certificate { get; set; }
    
        public virtual tblBloodGroup tblBloodGroup { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCertificate> tblCertificates { get; set; }
        public virtual tblCollege tblCollege { get; set; }
        public virtual tblCourse tblCourse { get; set; }
        public virtual tblDistrict tblDistrict { get; set; }
        public virtual tblState tblState { get; set; }
        public virtual tblStream tblStream { get; set; }
    }
}
